import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import supabase from "./api/supabase";

export async function getStaticProps() {
  let { data: members, error } = await supabase.from("members").select("*");
  return {
    props: {
      members,
    },
  };
}
export default function Home({ members = [] }) {
  const [subscribers, setSubscribers] = useState(() => members);
  const totalMeals = subscribers.filter(
    (subscriber) => subscriber.have_meal
  ).length;

  useEffect(() => {
    const mySubscription = supabase
      .from("members")
      .on("INSERT", (payload) => {
        setSubscribers((prev) => prev.push(payload.new));
      })
      .on("UPDATE", (payload) => {
        const idx = subscribers.findIndex(
          (subscriber) => subscriber.id === payload.old.id
        );
        const cloneSubscribers = structuredClone(subscribers);
        cloneSubscribers.splice(idx, 1, payload.new);
        setSubscribers(cloneSubscribers);
      })
      .subscribe();
    return () => supabase.removeSubscription(mySubscription);
  }, [subscribers]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Total meals {totalMeals}</h1>

        <pre>{JSON.stringify(subscribers, null, 2)}</pre>
      </main>
    </div>
  );
}
