import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import supabase from "./api/supabase";
import { DatePicker, Space, Table } from "antd";
import moment from "moment";

export async function getStaticProps() {
  let { data: members, error } = await supabase.from("members").select("*");
  if (error) {
    throw new Error(error);
  }
  return {
    props: {
      members,
    },
  };
}
export default function Home({ members = [] }) {
  const [subscribers, setSubscribers] = useState(members);
  const totalMeals = subscribers.filter(
    (subscriber) => subscriber.have_meal
  ).length;

  useEffect(() => {
    const mySubscription = supabase
      .from("members")
      .on("INSERT", (payload) => {
        setSubscribers([...subscribers, payload.new]);
      })
      .on("UPDATE", (payload) => {
        const idx = subscribers.findIndex(
          (subscriber) => subscriber.id === payload.old.id
        );
        const cloneSubscribers = structuredClone(subscribers);
        cloneSubscribers.splice(idx, 1, payload.new);
        setSubscribers(cloneSubscribers);
      })
      .subscribe();
    return () => supabase.removeSubscription(mySubscription);
  }, [subscribers]);

  const columns = [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
    },
    {
      title: "User Name",
      dataIndex: "user_name",
      key: "user_name",
    },
    {
      title: "Meal",
      dataIndex: "have_meal",
      key: "have_meal",
      render: (val) => (val ? "✔" : "𝙭"),
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Meal Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className={styles.title}>Total meals {totalMeals}</h2>
        <Space direction="vertical">
          <DatePicker onChange={() => undefined} value={moment()} />
          <Table dataSource={subscribers} columns={columns} />
        </Space>
      </main>
    </div>
  );
}
